<?xml version="1.0" encoding="utf-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_omni_robot">
  <!-- robot_state_publisher no longer support tf_prefix in ROS Noetic...-->
  <xacro:arg name="link_prefix" default="" />

  <xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/simple-omni-robot.gazebo" />
  <!-- According TB3 -->
  <xacro:property name="RADIUS" value="0.105" />
  <xacro:property name="HEIGHT" value="0.192" />

  <xacro:hokuyo_utm30lx name="$(arg link_prefix)/lidar" parent="$(arg link_prefix)/base_link" ros_topic="laser"
                        update_rate="30" ray_count="270"
                        min_angle="-135" max_angle="135">
    <!-- Place lidar on the top and back of robot, lidar size is W60xD60xH87mm -->
    <origin xyz="${RADIUS*-1+0.03} 0.0 ${HEIGHT/2+0.0435}" rpy="0 0 0" />
  </xacro:hokuyo_utm30lx>

  <!-- Links -->
  <link name="$(arg link_prefix)/head">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 0.02" />
      </geometry>
    </visual>
  </link>

  <link name="$(arg link_prefix)/base_footprint">
    <visual>
      <origin xyz="0 0 0.005" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${RADIUS}" length="0.01" />
      </geometry>
    </visual>
  </link>

  <link name="$(arg link_prefix)/base_link">
    <inertial>
      <!-- <origin xyz="0 0 ${HEIGHT/2}" rpy="0 0 0" /> -->
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="50.0" />
      <!-- for a cylinder: ixx = 0.083 * mass * (3*r*r + h*h), when mass is 1, equal to 0.003974787 -->
      <!-- for a cylinder: ixy = 0 -->
      <!-- for a cylinder: ixz = 0 -->
      <!-- for a cylinder: iyy = 0.083 * mass * (3*r*r + h*h), when mass is 1, equal to 0.003974787 -->
      <!-- for a cylinder: iyz = 0 -->
      <!-- for a cylinder: izz = 0.5 * mass * (r*r, when mass is 1, equal to 0.0055125 -->)
      <!-- http://gazebosim.org/tutorials?tut=inertia&cat=build_robot -->
      <!-- https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
      <!-- <inertia
        ixx="0.19873935"
        ixy="0.0"
        ixz="0.0"
        iyy="0.19873935"
        iyz="0.0"
        izz="0.275625" /> -->
      <inertia
        ixx="50.0"
        ixy="0.0"
        ixz="0.0"
        iyy="50.0"
        iyz="0.0"
        izz="50.0" />
    </inertial>

    <visual>
      <geometry>
        <cylinder radius="${RADIUS}" length="${HEIGHT}" />
      </geometry>
    </visual>

    <collision name="baselink">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${RADIUS}" length="${HEIGHT+0.05}" />
      </geometry>
    </collision>
  </link>

  <!-- Joints -->
  <joint name="head_joint" type="fixed">
    <origin xyz="${RADIUS} 0 ${HEIGHT/2}" rpy="0 0 0" />
    <parent link="$(arg link_prefix)/base_link"/>
    <child link="$(arg link_prefix)/head" />
  </joint>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0.0 0 ${HEIGHT/2+0.01}" rpy="0 0 0" />
    <parent link="$(arg link_prefix)/base_footprint"/>
    <child link="$(arg link_prefix)/base_link" />
  </joint>

  <xacro:simple_omni_robot_gazebo prefix="$(arg link_prefix)" />
</robot>
